use std::abi::sol::{self, Int24, Uint24}
use std::evm::{Address, Create, Evm, Log, RawMem}
use super::mock_time_uniswap_v3_pool::MockTimeUniswapV3Pool

const POOL_DEPLOYED_TOPIC: u256 = 0xf0d1eeab175eee2e20b8dc452773bf2257b25724b323b42bc6e5b4616233ae1f

fn emit_pool_deployed(_ pool: Address) uses (evm: mut Evm) {
    let ptr = std::evm::mem::alloc(0)
    evm.mstore(addr: ptr, value: pool.inner)
    evm.log1(offset: ptr, len: 32, topic0: POOL_DEPLOYED_TOPIC)
}

msg MockTimeUniswapV3PoolDeployerMsg {
    #[selector = sol("deploy(address,address,address,uint24,int24)")]
    Deploy {
        factory: Address,
        token0: Address,
        token1: Address,
        fee: Uint24,
        tickSpacing: Int24,
    } -> u256,
}

pub contract MockTimeUniswapV3PoolDeployer uses (evm: mut Evm) {
    recv MockTimeUniswapV3PoolDeployerMsg {
        Deploy { factory, token0, token1, fee, tickSpacing } -> u256
        uses (mut evm)
        {
            let pool = evm
                .create2<MockTimeUniswapV3Pool>(
                    value: 0,
                    args: (factory, token0, token1, fee, tickSpacing),
                    salt: 0,
                )
            emit_pool_deployed(pool)
            pool.inner
        }
    }
}
