use std::abi::sol
use std::evm::{Ctx, Evm}

pub fn most_significant_bit(_ x: u256) -> u8 {
    assert(x > 0)

    let mut value = x
    let mut r: u256 = 0

    while value > 1 {
        value = value >> 1
        r = r + 1
    }

    r.downcast_unchecked()
}

pub fn least_significant_bit(_ x: u256) -> u8 {
    assert(x > 0)

    let mut value = x
    let mut r: u256 = 0

    while (value & 1) == 0 {
        value = value >> 1
        r = r + 1
    }

    r.downcast_unchecked()
}

msg BitMathTestMsg {
    #[selector = sol("mostSignificantBit(uint256)")]
    MostSignificantBit { x: u256 } -> u8,

    #[selector = sol("getGasCostOfMostSignificantBit(uint256)")]
    GetGasCostOfMostSignificantBit { x: u256 } -> u256,

    #[selector = sol("leastSignificantBit(uint256)")]
    LeastSignificantBit { x: u256 } -> u8,

    #[selector = sol("getGasCostOfLeastSignificantBit(uint256)")]
    GetGasCostOfLeastSignificantBit { x: u256 } -> u256,
}

pub contract BitMathTest uses (evm: Evm) {
    recv BitMathTestMsg {
        MostSignificantBit { x } -> u8 {
            most_significant_bit(x)
        }

        GetGasCostOfMostSignificantBit { x } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            most_significant_bit(x)
            gas_before - evm.gas()
        }

        LeastSignificantBit { x } -> u8 {
            least_significant_bit(x)
        }

        GetGasCostOfLeastSignificantBit { x } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            least_significant_bit(x)
            gas_before - evm.gas()
        }
    }
}
