use std::abi::sol
use std::evm::{Ctx, Evm}

#[arithmetic(unchecked)]
pub fn most_significant_bit(_ x: u256) -> u8 {
    assert(x > 0)

    let mut value = x
    let mut r: u256 = 0

    while value > 1 {
        value = value >> 1
        r = r + 1
    }

    r.downcast_unchecked()
}

#[arithmetic(unchecked)]
pub fn least_significant_bit(_ x: u256) -> u8 {
    assert(x > 0)

    let mut value = x
    let mut r: u256 = 0

    while (value & 1) == 0 {
        value = value >> 1
        r = r + 1
    }

    r.downcast_unchecked()
}

msg BitMathTestMsg {
    #[selector = sol("mostSignificantBit(uint256)")]
    MostSignificantBit { x: u256 } -> u8,

    #[selector = sol("getGasCostOfMostSignificantBit(uint256)")]
    GetGasCostOfMostSignificantBit { x: u256 } -> u256,

    #[selector = sol("leastSignificantBit(uint256)")]
    LeastSignificantBit { x: u256 } -> u8,

    #[selector = sol("getGasCostOfLeastSignificantBit(uint256)")]
    GetGasCostOfLeastSignificantBit { x: u256 } -> u256,
}

msg BitMathEchidnaTestMsg {
    #[selector = sol("mostSignificantBitInvariant(uint256)")]
    MostSignificantBitInvariant { input: u256 },

    #[selector = sol("leastSignificantBitInvariant(uint256)")]
    LeastSignificantBitInvariant { input: u256 },
}

pub contract BitMathTest uses (evm: Evm) {
    recv BitMathTestMsg {
        MostSignificantBit { x } -> u8 {
            most_significant_bit(x)
        }

        GetGasCostOfMostSignificantBit { x } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            most_significant_bit(x)
            gas_before - evm.gas()
        }

        LeastSignificantBit { x } -> u8 {
            least_significant_bit(x)
        }

        GetGasCostOfLeastSignificantBit { x } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            least_significant_bit(x)
            gas_before - evm.gas()
        }
    }
}

pub contract BitMathEchidnaTest {
    recv BitMathEchidnaTestMsg {
        MostSignificantBitInvariant { input } {
            let msb = most_significant_bit(input)
            assert(input >= ((1 as u256) << (msb as u256)))
            assert(msb == 255 || input < ((1 as u256) << ((msb + 1) as u256)))
        }

        LeastSignificantBitInvariant { input } {
            let lsb = least_significant_bit(input)
            assert(input & ((1 as u256) << (lsb as u256)) != 0)
            assert(input & (((1 as u256) << (lsb as u256)) - 1) == 0)
        }
    }
}
