use std::abi::sol
use std::evm::{Ctx, Evm}

const MASK_U128: u256 = 0xffffffffffffffffffffffffffffffff
const MASK_U64: u256 = 0xffffffffffffffff
const MASK_U32: u256 = 0xffffffff
const MASK_U16: u256 = 0xffff
const MASK_U8: u256 = 0xff

#[arithmetic(unchecked)]
#[inline(always)]
pub fn most_significant_bit(_ x: u256) -> u8 {
    assert(x > 0)

    let mut value = x
    let mut r: u256 = 0

    if value >= (1 << 128) {
        value = value >> 128
        r = r + 128
    }
    if value >= (1 << 64) {
        value = value >> 64
        r = r + 64
    }
    if value >= (1 << 32) {
        value = value >> 32
        r = r + 32
    }
    if value >= (1 << 16) {
        value = value >> 16
        r = r + 16
    }
    if value >= (1 << 8) {
        value = value >> 8
        r = r + 8
    }
    if value >= (1 << 4) {
        value = value >> 4
        r = r + 4
    }
    if value >= (1 << 2) {
        value = value >> 2
        r = r + 2
    }
    if value >= (1 << 1) {
        r = r + 1
    }

    r.downcast_unchecked()
}

#[arithmetic(unchecked)]
#[inline(always)]
pub fn least_significant_bit(_ x: u256) -> u8 {
    assert(x > 0)

    let mut value = x
    let mut r: u256 = 0

    r = 255
    if (value & MASK_U128) > 0 {
        r = r - 128
    } else {
        value = value >> 128
    }
    if (value & MASK_U64) > 0 {
        r = r - 64
    } else {
        value = value >> 64
    }
    if (value & MASK_U32) > 0 {
        r = r - 32
    } else {
        value = value >> 32
    }
    if (value & MASK_U16) > 0 {
        r = r - 16
    } else {
        value = value >> 16
    }
    if (value & MASK_U8) > 0 {
        r = r - 8
    } else {
        value = value >> 8
    }
    if (value & 0xf) > 0 {
        r = r - 4
    } else {
        value = value >> 4
    }
    if (value & 0x3) > 0 {
        r = r - 2
    } else {
        value = value >> 2
    }
    if (value & 0x1) > 0 {
        r = r - 1
    }

    r.downcast_unchecked()
}

msg BitMathTestMsg {
    #[selector = sol("mostSignificantBit(uint256)")]
    MostSignificantBit { x: u256 } -> u8,

    #[selector = sol("getGasCostOfMostSignificantBit(uint256)")]
    GetGasCostOfMostSignificantBit { x: u256 } -> u256,

    #[selector = sol("leastSignificantBit(uint256)")]
    LeastSignificantBit { x: u256 } -> u8,

    #[selector = sol("getGasCostOfLeastSignificantBit(uint256)")]
    GetGasCostOfLeastSignificantBit { x: u256 } -> u256,
}

msg BitMathEchidnaTestMsg {
    #[selector = sol("mostSignificantBitInvariant(uint256)")]
    MostSignificantBitInvariant { input: u256 },

    #[selector = sol("leastSignificantBitInvariant(uint256)")]
    LeastSignificantBitInvariant { input: u256 },
}

pub contract BitMathTest uses (evm: Evm) {
    recv BitMathTestMsg {
        MostSignificantBit { x } -> u8 {
            most_significant_bit(x)
        }

        GetGasCostOfMostSignificantBit { x } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            most_significant_bit(x)
            gas_before - evm.gas()
        }

        LeastSignificantBit { x } -> u8 {
            least_significant_bit(x)
        }

        GetGasCostOfLeastSignificantBit { x } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            least_significant_bit(x)
            gas_before - evm.gas()
        }
    }
}

pub contract BitMathEchidnaTest {
    recv BitMathEchidnaTestMsg {
        MostSignificantBitInvariant { input } {
            let msb = most_significant_bit(input)
            assert(input >= ((1 as u256) << (msb as u256)))
            assert(msb == 255 || input < ((1 as u256) << ((msb + 1) as u256)))
        }

        LeastSignificantBitInvariant { input } {
            let lsb = least_significant_bit(input)
            assert(input & ((1 as u256) << (lsb as u256)) != 0)
            assert(input & (((1 as u256) << (lsb as u256)) - 1) == 0)
        }
    }
}
