use std::abi::sol
use std::evm::crypto::mulmod

const U256_MAX: u256 = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

#[arithmetic(unchecked)]
pub fn mul_div(_ a: u256, _ b: u256, denominator: u256) -> u256 {
    let mm = mulmod(a, b, U256_MAX)
    let mut prod0 = a * b
    let mut prod1 = (mm - prod0) - ((mm < prod0) as u256)

    if prod1 == 0 {
        assert(denominator > 0)
        return prod0 / denominator
    }

    assert(denominator > prod1)

    let remainder = mulmod(a, b, denominator)
    prod1 = prod1 - ((remainder > prod0) as u256)
    prod0 = prod0 - remainder

    let twos = (0 - denominator) & denominator
    let exact_denominator = denominator / twos
    prod0 = prod0 / twos
    let flipped_twos = ((0 - twos) / twos) + 1

    prod0 = prod0 | (prod1 * flipped_twos)

    let mut inv = (3 * exact_denominator) ^ 2
    inv = inv * (2 - (exact_denominator * inv))
    inv = inv * (2 - (exact_denominator * inv))
    inv = inv * (2 - (exact_denominator * inv))
    inv = inv * (2 - (exact_denominator * inv))
    inv = inv * (2 - (exact_denominator * inv))
    inv = inv * (2 - (exact_denominator * inv))

    prod0 * inv
}

#[arithmetic(unchecked)]
pub fn mul_div_rounding_up(_ a: u256, _ b: u256, denominator: u256) -> u256 {
    let mut result = mul_div(a, b, denominator)
    if mulmod(a, b, denominator) > 0 {
        assert(result < U256_MAX)
        result = result + 1
    }

    result
}

msg FullMathTestMsg {
    #[selector = sol("mulDiv(uint256,uint256,uint256)")]
    MulDiv { x: u256, y: u256, z: u256 } -> u256,

    #[selector = sol("mulDivRoundingUp(uint256,uint256,uint256)")]
    MulDivRoundingUp { x: u256, y: u256, z: u256 } -> u256,
}

pub contract FullMathTest {
    recv FullMathTestMsg {
        MulDiv { x, y, z } -> u256 {
            mul_div(x, y, denominator: z)
        }

        MulDivRoundingUp { x, y, z } -> u256 {
            mul_div_rounding_up(x, y, denominator: z)
        }
    }
}

msg FullMathEchidnaTestMsg {
    #[selector = sol("checkMulDivRounding(uint256,uint256,uint256)")]
    CheckMulDivRounding { x: u256, y: u256, d: u256 },

    #[selector = sol("checkMulDiv(uint256,uint256,uint256)")]
    CheckMulDiv { x: u256, y: u256, d: u256 },

    #[selector = sol("checkMulDivRoundingUp(uint256,uint256,uint256)")]
    CheckMulDivRoundingUp { x: u256, y: u256, d: u256 },
}

pub contract FullMathEchidnaTest {
    recv FullMathEchidnaTestMsg {
        CheckMulDivRounding { x, y, d } {
            assert(d > 0)

            let ceiled = mul_div_rounding_up(x, y, denominator: d)
            let floored = mul_div(x, y, denominator: d)

            if mulmod(x, y, d) > 0 {
                assert(ceiled - floored == 1)
            } else {
                assert(ceiled == floored)
            }
        }

        CheckMulDiv { x, y, d } {
            assert(d > 0)

            let z = mul_div(x, y, denominator: d)
            if x == 0 || y == 0 {
                assert(z == 0)
                return
            }

            let x2 = mul_div(z, d, denominator: y)
            let y2 = mul_div(z, d, denominator: x)
            assert(x2 <= x)
            assert(y2 <= y)

            assert(x - x2 < d)
            assert(y - y2 < d)
        }

        CheckMulDivRoundingUp { x, y, d } {
            assert(d > 0)

            let z = mul_div_rounding_up(x, y, denominator: d)
            if x == 0 || y == 0 {
                assert(z == 0)
                return
            }

            let x2 = mul_div(z, d, denominator: y)
            let y2 = mul_div(z, d, denominator: x)
            assert(x2 >= x)
            assert(y2 >= y)

            assert(x2 - x < d)
            assert(y2 - y < d)
        }
    }
}
