use std::evm::{Address, Ctx, Evm}

fn check_not_delegate_call(_ original: Address) uses (ctx: Ctx) {
    assert(ctx.address() == original)
}

fn can_be_delegate_called() -> u256 uses (ctx: Ctx) {
    ctx.timestamp() / 5
}

fn cannot_be_delegate_called(_ original: Address) -> u256 uses (ctx: Ctx) {
    check_not_delegate_call(original)
    can_be_delegate_called()
}

fn no_delegate_call_private(_ original: Address) uses (ctx: Ctx) {
    check_not_delegate_call(original)
}

msg NoDelegateCallTestMsg {
    #[selector = 0xf45f416e]
    CanBeDelegateCalled -> u256,

    #[selector = 0x423ecb05]
    CannotBeDelegateCalled -> u256,

    #[selector = 0x3045a6e0]
    GetGasCostOfCanBeDelegateCalled -> u256,

    #[selector = 0x3c7c8dd0]
    GetGasCostOfCannotBeDelegateCalled -> u256,

    #[selector = 0x64270164]
    CallsIntoNoDelegateCallFunction,
}

pub contract NoDelegateCallTest uses (ctx: Ctx, evm: mut Evm) {
    original: Address,

    init() uses (ctx, mut original) { original = ctx.address() }

    recv NoDelegateCallTestMsg {
        CanBeDelegateCalled -> u256 uses (ctx) {
            can_be_delegate_called()
        }

        CannotBeDelegateCalled -> u256 uses (ctx, original) {
            cannot_be_delegate_called(original)
        }

        GetGasCostOfCanBeDelegateCalled -> u256 uses (ctx, evm) {
            let gas_before = evm.gas()
            can_be_delegate_called()
            gas_before - evm.gas()
        }

        GetGasCostOfCannotBeDelegateCalled -> u256
        uses (ctx, evm, original)
        {
            let gas_before = evm.gas()
            cannot_be_delegate_called(original)
            gas_before - evm.gas()
        }

        CallsIntoNoDelegateCallFunction uses (ctx, original) {
            no_delegate_call_private(original)
        }
    }
}
