use std::evm::Evm
use super::fixed_point_96::{Q96, RESOLUTION}
use super::full_math::{mul_div, mul_div_rounding_up}
use super::unsafe_math::div_rounding_up

const MAX_U160: u256 = 0xffffffffffffffffffffffffffffffffffffffff
const U256_MAX: u256 = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

pub fn get_next_sqrt_price_from_input(
    sqrt_p_x96: u256,
    _ liquidity: u128,
    amount_in: u256,
    zero_for_one: bool,
) -> u256 {
    assert(sqrt_p_x96 <= MAX_U160)
    assert(sqrt_p_x96 > 0)
    assert(liquidity > 0)

    if zero_for_one {
        return get_next_sqrt_price_from_amount0_rounding_up(
            sqrt_p_x96,
            liquidity,
            amount: amount_in,
            add: true,
        )
    }

    get_next_sqrt_price_from_amount1_rounding_down(
        sqrt_p_x96,
        liquidity,
        amount: amount_in,
        add: true,
    )
}

pub fn get_next_sqrt_price_from_output(
    sqrt_p_x96: u256,
    _ liquidity: u128,
    amount_out: u256,
    zero_for_one: bool,
) -> u256 {
    assert(sqrt_p_x96 <= MAX_U160)
    assert(sqrt_p_x96 > 0)
    assert(liquidity > 0)

    if zero_for_one {
        return get_next_sqrt_price_from_amount1_rounding_down(
            sqrt_p_x96,
            liquidity,
            amount: amount_out,
            add: false,
        )
    }

    get_next_sqrt_price_from_amount0_rounding_up(
        sqrt_p_x96,
        liquidity,
        amount: amount_out,
        add: false,
    )
}

#[arithmetic(unchecked)]
pub fn get_next_sqrt_price_from_amount0_rounding_up(
    sqrt_p_x96: u256,
    _ liquidity: u128,
    amount: u256,
    add: bool,
) -> u256 {
    assert(sqrt_p_x96 <= MAX_U160)

    if amount == 0 {
        return sqrt_p_x96
    }

    let numerator1 = (liquidity as u256) << (RESOLUTION as u256)

    if add {
        let product = amount * sqrt_p_x96
        if product / amount == sqrt_p_x96 {
            let denominator = numerator1 + product
            if denominator >= numerator1 {
                return to_u160(mul_div_rounding_up(numerator1, sqrt_p_x96, denominator))
            }
        }

        let quotient = numerator1 / sqrt_p_x96
        assert(amount <= U256_MAX - quotient)
        return to_u160(
            div_rounding_up(numerator: numerator1, denominator: quotient + amount),
        )
    }

    let product = amount * sqrt_p_x96
    assert(product / amount == sqrt_p_x96 && numerator1 > product)

    to_u160(
        mul_div_rounding_up(numerator1, sqrt_p_x96, denominator: numerator1 - product),
    )
}

pub fn get_next_sqrt_price_from_amount1_rounding_down(
    sqrt_p_x96: u256,
    _ liquidity: u128,
    amount: u256,
    add: bool,
) -> u256 {
    assert(sqrt_p_x96 <= MAX_U160)

    let quotient = if amount <= MAX_U160 {
        (amount << (RESOLUTION as u256)) / (liquidity as u256)
    } else {
        mul_div(amount, Q96, denominator: liquidity as u256)
    }

    if add {
        return to_u160(sqrt_p_x96 + quotient)
    }

    let quotient = if amount <= MAX_U160 {
        div_rounding_up(
            numerator: amount << (RESOLUTION as u256),
            denominator: liquidity as u256,
        )
    } else {
        mul_div_rounding_up(amount, Q96, denominator: liquidity as u256)
    }

    assert(sqrt_p_x96 > quotient)
    sqrt_p_x96 - quotient
}

pub fn get_amount0_delta(
    sqrt_ratio_a_x96: u256,
    sqrt_ratio_b_x96: u256,
    _ liquidity: u128,
    _ round_up: bool,
) -> u256 {
    assert(sqrt_ratio_a_x96 <= MAX_U160)
    assert(sqrt_ratio_b_x96 <= MAX_U160)

    let mut sqrt_ratio_lower = sqrt_ratio_a_x96
    let mut sqrt_ratio_upper = sqrt_ratio_b_x96
    if sqrt_ratio_lower > sqrt_ratio_upper {
        sqrt_ratio_lower = sqrt_ratio_b_x96
        sqrt_ratio_upper = sqrt_ratio_a_x96
    }

    let numerator1 = (liquidity as u256) << (RESOLUTION as u256)
    let numerator2 = sqrt_ratio_upper - sqrt_ratio_lower

    assert(sqrt_ratio_lower > 0)

    if round_up {
        return div_rounding_up(
            numerator: mul_div_rounding_up(numerator1, numerator2, denominator: sqrt_ratio_upper),
            denominator: sqrt_ratio_lower,
        )
    }

    mul_div(numerator1, numerator2, denominator: sqrt_ratio_upper) / sqrt_ratio_lower
}

pub fn get_amount1_delta(
    sqrt_ratio_a_x96: u256,
    sqrt_ratio_b_x96: u256,
    _ liquidity: u128,
    _ round_up: bool,
) -> u256 {
    assert(sqrt_ratio_a_x96 <= MAX_U160)
    assert(sqrt_ratio_b_x96 <= MAX_U160)

    let mut sqrt_ratio_lower = sqrt_ratio_a_x96
    let mut sqrt_ratio_upper = sqrt_ratio_b_x96
    if sqrt_ratio_lower > sqrt_ratio_upper {
        sqrt_ratio_lower = sqrt_ratio_b_x96
        sqrt_ratio_upper = sqrt_ratio_a_x96
    }

    let delta = sqrt_ratio_upper - sqrt_ratio_lower
    if round_up {
        return mul_div_rounding_up(liquidity as u256, delta, denominator: Q96)
    }

    mul_div(liquidity as u256, delta, denominator: Q96)
}

pub fn to_u160(_ x: u256) -> u256 {
    assert(x <= MAX_U160)
    x
}

msg SqrtPriceMathTestMsg {
    #[selector = 0xaa58276a]
    GetNextSqrtPriceFromInput {
        sqrtP: u256,
        liquidity: u128,
        amountIn: u256,
        zeroForOne: bool,
    } -> u256,

    #[selector = 0x034d21e4]
    GetGasCostOfGetNextSqrtPriceFromInput {
        sqrtP: u256,
        liquidity: u128,
        amountIn: u256,
        zeroForOne: bool,
    } -> u256,

    #[selector = 0xfedf2b5f]
    GetNextSqrtPriceFromOutput {
        sqrtP: u256,
        liquidity: u128,
        amountOut: u256,
        zeroForOne: bool,
    } -> u256,

    #[selector = 0xe20f7ac0]
    GetGasCostOfGetNextSqrtPriceFromOutput {
        sqrtP: u256,
        liquidity: u128,
        amountOut: u256,
        zeroForOne: bool,
    } -> u256,

    #[selector = 0x2c32d4b6]
    GetAmount0Delta { sqrtLower: u256, sqrtUpper: u256, liquidity: u128, roundUp: bool } -> u256,

    #[selector = 0x48a0c5bd]
    GetAmount1Delta { sqrtLower: u256, sqrtUpper: u256, liquidity: u128, roundUp: bool } -> u256,

    #[selector = 0xd7cdaf71]
    GetGasCostOfGetAmount0Delta {
        sqrtLower: u256,
        sqrtUpper: u256,
        liquidity: u128,
        roundUp: bool,
    } -> u256,

    #[selector = 0xaf955e3b]
    GetGasCostOfGetAmount1Delta {
        sqrtLower: u256,
        sqrtUpper: u256,
        liquidity: u128,
        roundUp: bool,
    } -> u256,
}

pub contract SqrtPriceMathTest uses (evm: Evm) {
    recv SqrtPriceMathTestMsg {
        GetNextSqrtPriceFromInput { sqrtP, liquidity, amountIn, zeroForOne } -> u256 {
            get_next_sqrt_price_from_input(
                sqrt_p_x96: sqrtP,
                liquidity,
                amount_in: amountIn,
                zero_for_one: zeroForOne,
            )
        }

        GetGasCostOfGetNextSqrtPriceFromInput { sqrtP, liquidity, amountIn, zeroForOne } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            get_next_sqrt_price_from_input(
                sqrt_p_x96: sqrtP,
                liquidity,
                amount_in: amountIn,
                zero_for_one: zeroForOne,
            )
            gas_before - evm.gas()
        }

        GetNextSqrtPriceFromOutput { sqrtP, liquidity, amountOut, zeroForOne } -> u256 {
            get_next_sqrt_price_from_output(
                sqrt_p_x96: sqrtP,
                liquidity,
                amount_out: amountOut,
                zero_for_one: zeroForOne,
            )
        }

        GetGasCostOfGetNextSqrtPriceFromOutput { sqrtP, liquidity, amountOut, zeroForOne } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            get_next_sqrt_price_from_output(
                sqrt_p_x96: sqrtP,
                liquidity,
                amount_out: amountOut,
                zero_for_one: zeroForOne,
            )
            gas_before - evm.gas()
        }

        GetAmount0Delta { sqrtLower, sqrtUpper, liquidity, roundUp } -> u256 {
            get_amount0_delta(
                sqrt_ratio_a_x96: sqrtLower,
                sqrt_ratio_b_x96: sqrtUpper,
                liquidity,
                round_up: roundUp,
            )
        }

        GetAmount1Delta { sqrtLower, sqrtUpper, liquidity, roundUp } -> u256 {
            get_amount1_delta(
                sqrt_ratio_a_x96: sqrtLower,
                sqrt_ratio_b_x96: sqrtUpper,
                liquidity,
                round_up: roundUp,
            )
        }

        GetGasCostOfGetAmount0Delta { sqrtLower, sqrtUpper, liquidity, roundUp } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            get_amount0_delta(
                sqrt_ratio_a_x96: sqrtLower,
                sqrt_ratio_b_x96: sqrtUpper,
                liquidity,
                round_up: roundUp,
            )
            gas_before - evm.gas()
        }

        GetGasCostOfGetAmount1Delta { sqrtLower, sqrtUpper, liquidity, roundUp } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            get_amount1_delta(
                sqrt_ratio_a_x96: sqrtLower,
                sqrt_ratio_b_x96: sqrtUpper,
                liquidity,
                round_up: roundUp,
            )
            gas_before - evm.gas()
        }
    }
}
