use std::abi::sol::{self, Uint160}
use std::evm::crypto::mulmod
use std::evm::Evm
use super::fixed_point_96::{Q96, RESOLUTION}
use super::full_math::{mul_div, mul_div_rounding_up}
use super::safe_cast::to_int256
use super::unsafe_math::div_rounding_up

const MAX_U160: u256 = 0xffffffffffffffffffffffffffffffffffffffff
const U256_MAX: u256 = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

#[arithmetic(unchecked)]
pub fn get_next_sqrt_price_from_input(
    sqrt_p_x96: u256,
    _ liquidity: u128,
    amount_in: u256,
    zero_for_one: bool,
) -> u256 {
    assert(sqrt_p_x96 <= MAX_U160)
    assert(sqrt_p_x96 > 0)
    assert(liquidity > 0)

    if zero_for_one {
        return get_next_sqrt_price_from_amount0_rounding_up(
            sqrt_p_x96,
            liquidity,
            amount: amount_in,
            add: true,
        )
    }

    get_next_sqrt_price_from_amount1_rounding_down(
        sqrt_p_x96,
        liquidity,
        amount: amount_in,
        add: true,
    )
}

#[arithmetic(unchecked)]
pub fn get_next_sqrt_price_from_output(
    sqrt_p_x96: u256,
    _ liquidity: u128,
    amount_out: u256,
    zero_for_one: bool,
) -> u256 {
    assert(sqrt_p_x96 <= MAX_U160)
    assert(sqrt_p_x96 > 0)
    assert(liquidity > 0)

    if zero_for_one {
        return get_next_sqrt_price_from_amount1_rounding_down(
            sqrt_p_x96,
            liquidity,
            amount: amount_out,
            add: false,
        )
    }

    get_next_sqrt_price_from_amount0_rounding_up(
        sqrt_p_x96,
        liquidity,
        amount: amount_out,
        add: false,
    )
}

#[arithmetic(unchecked)]
pub fn get_next_sqrt_price_from_amount0_rounding_up(
    sqrt_p_x96: u256,
    _ liquidity: u128,
    amount: u256,
    add: bool,
) -> u256 {
    assert(sqrt_p_x96 <= MAX_U160)

    if amount == 0 {
        return sqrt_p_x96
    }

    let numerator1 = (liquidity as u256) << (RESOLUTION as u256)

    if add {
        let product = amount * sqrt_p_x96
        if product / amount == sqrt_p_x96 {
            let denominator = numerator1 + product
            if denominator >= numerator1 {
                return to_u160(mul_div_rounding_up(numerator1, sqrt_p_x96, denominator))
            }
        }

        let quotient = numerator1 / sqrt_p_x96
        assert(amount <= U256_MAX - quotient)
        return to_u160(
            div_rounding_up(numerator: numerator1, denominator: quotient + amount),
        )
    }

    let product = amount * sqrt_p_x96
    assert(product / amount == sqrt_p_x96 && numerator1 > product)

    to_u160(
        mul_div_rounding_up(numerator1, sqrt_p_x96, denominator: numerator1 - product),
    )
}

#[arithmetic(unchecked)]
pub fn get_next_sqrt_price_from_amount1_rounding_down(
    sqrt_p_x96: u256,
    _ liquidity: u128,
    amount: u256,
    add: bool,
) -> u256 {
    assert(sqrt_p_x96 <= MAX_U160)

    let quotient = if amount <= MAX_U160 {
        (amount << (RESOLUTION as u256)) / (liquidity as u256)
    } else {
        mul_div(amount, Q96, denominator: liquidity as u256)
    }

    if add {
        return to_u160(sqrt_p_x96 + quotient)
    }

    let quotient = if amount <= MAX_U160 {
        div_rounding_up(
            numerator: amount << (RESOLUTION as u256),
            denominator: liquidity as u256,
        )
    } else {
        mul_div_rounding_up(amount, Q96, denominator: liquidity as u256)
    }

    assert(sqrt_p_x96 > quotient)
    sqrt_p_x96 - quotient
}

#[arithmetic(unchecked)]
pub fn get_amount0_delta(
    sqrt_ratio_a_x96: u256,
    sqrt_ratio_b_x96: u256,
    _ liquidity: u128,
    _ round_up: bool,
) -> u256 {
    assert(sqrt_ratio_a_x96 <= MAX_U160)
    assert(sqrt_ratio_b_x96 <= MAX_U160)

    let mut sqrt_ratio_lower = sqrt_ratio_a_x96
    let mut sqrt_ratio_upper = sqrt_ratio_b_x96
    if sqrt_ratio_lower > sqrt_ratio_upper {
        sqrt_ratio_lower = sqrt_ratio_b_x96
        sqrt_ratio_upper = sqrt_ratio_a_x96
    }

    let numerator1 = (liquidity as u256) << (RESOLUTION as u256)
    let numerator2 = sqrt_ratio_upper - sqrt_ratio_lower

    assert(sqrt_ratio_lower > 0)

    if round_up {
        return div_rounding_up(
            numerator: mul_div_rounding_up(numerator1, numerator2, denominator: sqrt_ratio_upper),
            denominator: sqrt_ratio_lower,
        )
    }

    mul_div(numerator1, numerator2, denominator: sqrt_ratio_upper) / sqrt_ratio_lower
}

#[arithmetic(unchecked)]
pub fn get_amount1_delta(
    sqrt_ratio_a_x96: u256,
    sqrt_ratio_b_x96: u256,
    _ liquidity: u128,
    _ round_up: bool,
) -> u256 {
    assert(sqrt_ratio_a_x96 <= MAX_U160)
    assert(sqrt_ratio_b_x96 <= MAX_U160)

    let mut sqrt_ratio_lower = sqrt_ratio_a_x96
    let mut sqrt_ratio_upper = sqrt_ratio_b_x96
    if sqrt_ratio_lower > sqrt_ratio_upper {
        sqrt_ratio_lower = sqrt_ratio_b_x96
        sqrt_ratio_upper = sqrt_ratio_a_x96
    }

    let delta = sqrt_ratio_upper - sqrt_ratio_lower
    if round_up {
        return mul_div_rounding_up(liquidity as u256, delta, denominator: Q96)
    }

    mul_div(liquidity as u256, delta, denominator: Q96)
}

#[arithmetic(unchecked)]
pub fn to_u160(_ x: u256) -> u256 {
    assert(x <= MAX_U160)
    x
}

fn get_amount0_delta_signed(
    sqrt_ratio_a_x96: u256,
    sqrt_ratio_b_x96: u256,
    _ liquidity: i128,
) -> i256 {
    if liquidity < 0 {
        let liquidity_abs: u128 = (0 - (liquidity as i256)).downcast_unchecked()
        let amount = to_int256(
            get_amount0_delta(
                sqrt_ratio_a_x96,
                sqrt_ratio_b_x96,
                liquidity: liquidity_abs,
                round_up: false,
            ),
        )
        return 0 - amount
    }

    let liquidity_abs: u128 = liquidity.downcast_unchecked()
    to_int256(
        get_amount0_delta(
            sqrt_ratio_a_x96,
            sqrt_ratio_b_x96,
            liquidity: liquidity_abs,
            round_up: true,
        ),
    )
}

fn get_amount1_delta_signed(
    sqrt_ratio_a_x96: u256,
    sqrt_ratio_b_x96: u256,
    _ liquidity: i128,
) -> i256 {
    if liquidity < 0 {
        let liquidity_abs: u128 = (0 - (liquidity as i256)).downcast_unchecked()
        let amount = to_int256(
            get_amount1_delta(
                sqrt_ratio_a_x96,
                sqrt_ratio_b_x96,
                liquidity: liquidity_abs,
                round_up: false,
            ),
        )
        return 0 - amount
    }

    let liquidity_abs: u128 = liquidity.downcast_unchecked()
    to_int256(
        get_amount1_delta(
            sqrt_ratio_a_x96,
            sqrt_ratio_b_x96,
            liquidity: liquidity_abs,
            round_up: true,
        ),
    )
}

#[arithmetic(unchecked)]
fn amount0_delta_equivalency_holds(
    sqrt_p: u256,
    sqrt_q: u256,
    _ liquidity: u128,
    round_up: bool,
) -> bool {
    assert(sqrt_p >= sqrt_q)
    assert(sqrt_p > 0 && sqrt_q > 0)
    assert((sqrt_p * sqrt_q) / sqrt_p == sqrt_q)

    let numerator1 = (liquidity as u256) << (RESOLUTION as u256)
    let numerator2 = sqrt_p - sqrt_q
    let denominator = sqrt_p * sqrt_q
    let safe_result = if round_up {
        mul_div_rounding_up(numerator1, numerator2, denominator)
    } else {
        mul_div(numerator1, numerator2, denominator)
    }
    let full_result = get_amount0_delta(
        sqrt_ratio_a_x96: sqrt_q,
        sqrt_ratio_b_x96: sqrt_p,
        liquidity,
        round_up,
    )

    safe_result == full_result
}

msg SqrtPriceMathTestMsg {
    #[selector = 0xaa58276a]
    GetNextSqrtPriceFromInput {
        sqrtP: u256,
        liquidity: u128,
        amountIn: u256,
        zeroForOne: bool,
    } -> u256,

    #[selector = 0x034d21e4]
    GetGasCostOfGetNextSqrtPriceFromInput {
        sqrtP: u256,
        liquidity: u128,
        amountIn: u256,
        zeroForOne: bool,
    } -> u256,

    #[selector = 0xfedf2b5f]
    GetNextSqrtPriceFromOutput {
        sqrtP: u256,
        liquidity: u128,
        amountOut: u256,
        zeroForOne: bool,
    } -> u256,

    #[selector = 0xe20f7ac0]
    GetGasCostOfGetNextSqrtPriceFromOutput {
        sqrtP: u256,
        liquidity: u128,
        amountOut: u256,
        zeroForOne: bool,
    } -> u256,

    #[selector = 0x2c32d4b6]
    GetAmount0Delta { sqrtLower: u256, sqrtUpper: u256, liquidity: u128, roundUp: bool } -> u256,

    #[selector = 0x48a0c5bd]
    GetAmount1Delta { sqrtLower: u256, sqrtUpper: u256, liquidity: u128, roundUp: bool } -> u256,

    #[selector = 0xd7cdaf71]
    GetGasCostOfGetAmount0Delta {
        sqrtLower: u256,
        sqrtUpper: u256,
        liquidity: u128,
        roundUp: bool,
    } -> u256,

    #[selector = 0xaf955e3b]
    GetGasCostOfGetAmount1Delta {
        sqrtLower: u256,
        sqrtUpper: u256,
        liquidity: u128,
        roundUp: bool,
    } -> u256,
}

pub contract SqrtPriceMathTest uses (evm: Evm) {
    recv SqrtPriceMathTestMsg {
        GetNextSqrtPriceFromInput { sqrtP, liquidity, amountIn, zeroForOne } -> u256 {
            get_next_sqrt_price_from_input(
                sqrt_p_x96: sqrtP,
                liquidity,
                amount_in: amountIn,
                zero_for_one: zeroForOne,
            )
        }

        GetGasCostOfGetNextSqrtPriceFromInput { sqrtP, liquidity, amountIn, zeroForOne } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            get_next_sqrt_price_from_input(
                sqrt_p_x96: sqrtP,
                liquidity,
                amount_in: amountIn,
                zero_for_one: zeroForOne,
            )
            gas_before - evm.gas()
        }

        GetNextSqrtPriceFromOutput { sqrtP, liquidity, amountOut, zeroForOne } -> u256 {
            get_next_sqrt_price_from_output(
                sqrt_p_x96: sqrtP,
                liquidity,
                amount_out: amountOut,
                zero_for_one: zeroForOne,
            )
        }

        GetGasCostOfGetNextSqrtPriceFromOutput { sqrtP, liquidity, amountOut, zeroForOne } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            get_next_sqrt_price_from_output(
                sqrt_p_x96: sqrtP,
                liquidity,
                amount_out: amountOut,
                zero_for_one: zeroForOne,
            )
            gas_before - evm.gas()
        }

        GetAmount0Delta { sqrtLower, sqrtUpper, liquidity, roundUp } -> u256 {
            get_amount0_delta(
                sqrt_ratio_a_x96: sqrtLower,
                sqrt_ratio_b_x96: sqrtUpper,
                liquidity,
                round_up: roundUp,
            )
        }

        GetAmount1Delta { sqrtLower, sqrtUpper, liquidity, roundUp } -> u256 {
            get_amount1_delta(
                sqrt_ratio_a_x96: sqrtLower,
                sqrt_ratio_b_x96: sqrtUpper,
                liquidity,
                round_up: roundUp,
            )
        }

        GetGasCostOfGetAmount0Delta { sqrtLower, sqrtUpper, liquidity, roundUp } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            get_amount0_delta(
                sqrt_ratio_a_x96: sqrtLower,
                sqrt_ratio_b_x96: sqrtUpper,
                liquidity,
                round_up: roundUp,
            )
            gas_before - evm.gas()
        }

        GetGasCostOfGetAmount1Delta { sqrtLower, sqrtUpper, liquidity, roundUp } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            get_amount1_delta(
                sqrt_ratio_a_x96: sqrtLower,
                sqrt_ratio_b_x96: sqrtUpper,
                liquidity,
                round_up: roundUp,
            )
            gas_before - evm.gas()
        }
    }
}

msg SqrtPriceMathEchidnaTestMsg {
    #[selector = sol("mulDivRoundingUpInvariants(uint256,uint256,uint256)")]
    MulDivRoundingUpInvariants { x: u256, y: u256, z: u256 },

    #[selector = sol(
        "getNextSqrtPriceFromInputInvariants(uint160,uint128,uint256,bool)",
    )]
    GetNextSqrtPriceFromInputInvariants {
        sqrtP: Uint160,
        liquidity: u128,
        amountIn: u256,
        zeroForOne: bool,
    },

    #[selector = sol(
        "getNextSqrtPriceFromOutputInvariants(uint160,uint128,uint256,bool)",
    )]
    GetNextSqrtPriceFromOutputInvariants {
        sqrtP: Uint160,
        liquidity: u128,
        amountOut: u256,
        zeroForOne: bool,
    },

    #[selector = sol(
        "getNextSqrtPriceFromAmount0RoundingUpInvariants(uint160,uint128,uint256,bool)",
    )]
    GetNextSqrtPriceFromAmount0RoundingUpInvariants {
        sqrtPX96: Uint160,
        liquidity: u128,
        amount: u256,
        add: bool,
    },

    #[selector = sol(
        "getNextSqrtPriceFromAmount1RoundingDownInvariants(uint160,uint128,uint256,bool)",
    )]
    GetNextSqrtPriceFromAmount1RoundingDownInvariants {
        sqrtPX96: Uint160,
        liquidity: u128,
        amount: u256,
        add: bool,
    },

    #[selector = sol("getAmount0DeltaInvariants(uint160,uint160,uint128)")]
    GetAmount0DeltaInvariants { sqrtP: Uint160, sqrtQ: Uint160, liquidity: u128 },

    #[selector = sol(
        "getAmount0DeltaEquivalency(uint160,uint160,uint128,bool)",
    )]
    GetAmount0DeltaEquivalency { sqrtP: Uint160, sqrtQ: Uint160, liquidity: u128, roundUp: bool },

    #[selector = sol("getAmount1DeltaInvariants(uint160,uint160,uint128)")]
    GetAmount1DeltaInvariants { sqrtP: Uint160, sqrtQ: Uint160, liquidity: u128 },

    #[selector = sol("getAmount0DeltaSignedInvariants(uint160,uint160,int128)")]
    GetAmount0DeltaSignedInvariants { sqrtP: Uint160, sqrtQ: Uint160, liquidity: i128 },

    #[selector = sol("getAmount1DeltaSignedInvariants(uint160,uint160,int128)")]
    GetAmount1DeltaSignedInvariants { sqrtP: Uint160, sqrtQ: Uint160, liquidity: i128 },

    #[selector = sol("getOutOfRangeMintInvariants(uint160,uint160,int128)")]
    GetOutOfRangeMintInvariants { sqrtA: Uint160, sqrtB: Uint160, liquidity: i128 },

    #[selector = sol(
        "getInRangeMintInvariants(uint160,uint160,uint160,int128)",
    )]
    GetInRangeMintInvariants {
        sqrtLower: Uint160,
        sqrtCurrent: Uint160,
        sqrtUpper: Uint160,
        liquidity: i128,
    },
}

pub contract SqrtPriceMathEchidnaTest {
    recv SqrtPriceMathEchidnaTestMsg {
        MulDivRoundingUpInvariants { x, y, z } {
            assert(z > 0)
            let not_rounded_up = mul_div(x, y, denominator: z)
            let rounded_up = mul_div_rounding_up(x, y, denominator: z)
            assert(rounded_up >= not_rounded_up)
            assert(rounded_up - not_rounded_up < 2)

            if rounded_up - not_rounded_up == 1 {
                assert(mulmod(x, y, z) > 0)
            } else {
                assert(mulmod(x, y, z) == 0)
            }
        }

        GetNextSqrtPriceFromInputInvariants { sqrtP, liquidity, amountIn, zeroForOne } {
            let sqrt_q = get_next_sqrt_price_from_input(
                sqrt_p_x96: sqrtP.val,
                liquidity,
                amount_in: amountIn,
                zero_for_one: zeroForOne,
            )

            if zeroForOne {
                assert(sqrt_q <= sqrtP.val)
                assert(
                    amountIn
                        >= get_amount0_delta(
                            sqrt_ratio_a_x96: sqrt_q,
                            sqrt_ratio_b_x96: sqrtP.val,
                            liquidity,
                            round_up: true,
                        ),
                )
            } else {
                assert(sqrt_q >= sqrtP.val)
                assert(
                    amountIn
                        >= get_amount1_delta(
                            sqrt_ratio_a_x96: sqrtP.val,
                            sqrt_ratio_b_x96: sqrt_q,
                            liquidity,
                            round_up: true,
                        ),
                )
            }
        }

        GetNextSqrtPriceFromOutputInvariants { sqrtP, liquidity, amountOut, zeroForOne } {
            let sqrt_q = get_next_sqrt_price_from_output(
                sqrt_p_x96: sqrtP.val,
                liquidity,
                amount_out: amountOut,
                zero_for_one: zeroForOne,
            )

            if zeroForOne {
                assert(sqrt_q <= sqrtP.val)
                assert(
                    amountOut
                        <= get_amount1_delta(
                            sqrt_ratio_a_x96: sqrt_q,
                            sqrt_ratio_b_x96: sqrtP.val,
                            liquidity,
                            round_up: false,
                        ),
                )
            } else {
                assert(sqrt_q > 0)
                assert(sqrt_q >= sqrtP.val)
                assert(
                    amountOut
                        <= get_amount0_delta(
                            sqrt_ratio_a_x96: sqrtP.val,
                            sqrt_ratio_b_x96: sqrt_q,
                            liquidity,
                            round_up: false,
                        ),
                )
            }
        }

        GetNextSqrtPriceFromAmount0RoundingUpInvariants { sqrtPX96, liquidity, amount, add } {
            assert(sqrtPX96.val > 0)
            assert(liquidity > 0)
            let sqrt_q_x96 = get_next_sqrt_price_from_amount0_rounding_up(
                sqrt_p_x96: sqrtPX96.val,
                liquidity,
                amount,
                add,
            )

            if add {
                assert(sqrt_q_x96 <= sqrtPX96.val)
            } else {
                assert(sqrt_q_x96 >= sqrtPX96.val)
            }

            if amount == 0 {
                assert(sqrtPX96.val == sqrt_q_x96)
            }
        }

        GetNextSqrtPriceFromAmount1RoundingDownInvariants { sqrtPX96, liquidity, amount, add } {
            assert(sqrtPX96.val > 0)
            assert(liquidity > 0)
            let sqrt_q_x96 = get_next_sqrt_price_from_amount1_rounding_down(
                sqrt_p_x96: sqrtPX96.val,
                liquidity,
                amount,
                add,
            )

            if add {
                assert(sqrt_q_x96 >= sqrtPX96.val)
            } else {
                assert(sqrt_q_x96 <= sqrtPX96.val)
            }

            if amount == 0 {
                assert(sqrtPX96.val == sqrt_q_x96)
            }
        }

        GetAmount0DeltaInvariants { sqrtP, sqrtQ, liquidity } {
            assert(sqrtP.val > 0 && sqrtQ.val > 0)

            let amount0_down = get_amount0_delta(
                sqrt_ratio_a_x96: sqrtQ.val,
                sqrt_ratio_b_x96: sqrtP.val,
                liquidity,
                round_up: false,
            )
            assert(
                amount0_down
                    == get_amount0_delta(
                        sqrt_ratio_a_x96: sqrtP.val,
                        sqrt_ratio_b_x96: sqrtQ.val,
                        liquidity,
                        round_up: false,
                    ),
            )

            let amount0_up = get_amount0_delta(
                sqrt_ratio_a_x96: sqrtQ.val,
                sqrt_ratio_b_x96: sqrtP.val,
                liquidity,
                round_up: true,
            )
            assert(
                amount0_up
                    == get_amount0_delta(
                        sqrt_ratio_a_x96: sqrtP.val,
                        sqrt_ratio_b_x96: sqrtQ.val,
                        liquidity,
                        round_up: true,
                    ),
            )

            assert(amount0_down <= amount0_up)
            assert(amount0_up - amount0_down < 2)
        }

        GetAmount0DeltaEquivalency { sqrtP, sqrtQ, liquidity, roundUp } {
            assert(
                amount0_delta_equivalency_holds(
                    sqrt_p: sqrtP.val,
                    sqrt_q: sqrtQ.val,
                    liquidity,
                    round_up: roundUp,
                ),
            )
        }

        GetAmount1DeltaInvariants { sqrtP, sqrtQ, liquidity } {
            assert(sqrtP.val > 0 && sqrtQ.val > 0)

            let amount1_down = get_amount1_delta(
                sqrt_ratio_a_x96: sqrtP.val,
                sqrt_ratio_b_x96: sqrtQ.val,
                liquidity,
                round_up: false,
            )
            assert(
                amount1_down
                    == get_amount1_delta(
                        sqrt_ratio_a_x96: sqrtQ.val,
                        sqrt_ratio_b_x96: sqrtP.val,
                        liquidity,
                        round_up: false,
                    ),
            )

            let amount1_up = get_amount1_delta(
                sqrt_ratio_a_x96: sqrtP.val,
                sqrt_ratio_b_x96: sqrtQ.val,
                liquidity,
                round_up: true,
            )
            assert(
                amount1_up
                    == get_amount1_delta(
                        sqrt_ratio_a_x96: sqrtQ.val,
                        sqrt_ratio_b_x96: sqrtP.val,
                        liquidity,
                        round_up: true,
                    ),
            )

            assert(amount1_down <= amount1_up)
            assert(amount1_up - amount1_down < 2)
        }

        GetAmount0DeltaSignedInvariants { sqrtP, sqrtQ, liquidity } {
            assert(sqrtP.val > 0 && sqrtQ.val > 0)

            let amount0 = get_amount0_delta_signed(
                sqrt_ratio_a_x96: sqrtQ.val,
                sqrt_ratio_b_x96: sqrtP.val,
                liquidity,
            )
            if liquidity < 0 {
                assert(amount0 <= 0)
            }
            if liquidity > 0 {
                if sqrtP.val == sqrtQ.val {
                    assert(amount0 == 0)
                } else {
                    assert(amount0 > 0)
                }
            }
            if liquidity == 0 {
                assert(amount0 == 0)
            }
        }

        GetAmount1DeltaSignedInvariants { sqrtP, sqrtQ, liquidity } {
            assert(sqrtP.val > 0 && sqrtQ.val > 0)

            let amount1 = get_amount1_delta_signed(
                sqrt_ratio_a_x96: sqrtP.val,
                sqrt_ratio_b_x96: sqrtQ.val,
                liquidity,
            )
            if liquidity < 0 {
                assert(amount1 <= 0)
            }
            if liquidity > 0 {
                if sqrtP.val == sqrtQ.val {
                    assert(amount1 == 0)
                } else {
                    assert(amount1 > 0)
                }
            }
            if liquidity == 0 {
                assert(amount1 == 0)
            }
        }

        GetOutOfRangeMintInvariants { sqrtA, sqrtB, liquidity } {
            assert(sqrtA.val > 0 && sqrtB.val > 0)
            assert(liquidity > 0)

            let amount0 = get_amount0_delta_signed(
                sqrt_ratio_a_x96: sqrtA.val,
                sqrt_ratio_b_x96: sqrtB.val,
                liquidity,
            )
            let amount1 = get_amount1_delta_signed(
                sqrt_ratio_a_x96: sqrtA.val,
                sqrt_ratio_b_x96: sqrtB.val,
                liquidity,
            )

            if sqrtA.val == sqrtB.val {
                assert(amount0 == 0)
                assert(amount1 == 0)
            } else {
                assert(amount0 > 0)
                assert(amount1 > 0)
            }
        }

        GetInRangeMintInvariants { sqrtLower, sqrtCurrent, sqrtUpper, liquidity } {
            assert(sqrtLower.val > 0)
            assert(sqrtLower.val < sqrtUpper.val)
            assert(
                sqrtLower.val <= sqrtCurrent.val && sqrtCurrent.val <= sqrtUpper.val,
            )
            assert(liquidity > 0)

            let amount0 = get_amount0_delta_signed(
                sqrt_ratio_a_x96: sqrtCurrent.val,
                sqrt_ratio_b_x96: sqrtUpper.val,
                liquidity,
            )
            let amount1 = get_amount1_delta_signed(
                sqrt_ratio_a_x96: sqrtLower.val,
                sqrt_ratio_b_x96: sqrtCurrent.val,
                liquidity,
            )

            assert(amount0 > 0 || amount1 > 0)
        }
    }
}
