use std::evm::Evm

const MIN_TICK: i256 = -887272
const MAX_TICK: i256 = 887272
const MIN_SQRT_RATIO: u256 = 4295128739
const MAX_SQRT_RATIO: u256 = 1461446703485210103287273052203988822378723970342
const MAX_U160: u256 = 0xffffffffffffffffffffffffffffffffffffffff
const U256_MAX: u256 = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

#[arithmetic(unchecked)]
pub fn get_sqrt_ratio_at_tick(tick: i256) -> u256 {
    let abs_tick: u256 = if tick < 0 {
        (0 - tick).downcast_unchecked()
    } else {
        tick.downcast_unchecked()
    }
    assert(abs_tick <= MAX_TICK.downcast_unchecked())

    let mut ratio = if (abs_tick & 0x1) != 0 {
        0xfffcb933bd6fad37aa2d162d1a594001
    } else {
        0x100000000000000000000000000000000
    }
    if (abs_tick & 0x2) != 0 {
        ratio = (ratio * 0xfff97272373d413259a46990580e213a) >> 128
    }
    if (abs_tick & 0x4) != 0 {
        ratio = (ratio * 0xfff2e50f5f656932ef12357cf3c7fdcc) >> 128
    }
    if (abs_tick & 0x8) != 0 {
        ratio = (ratio * 0xffe5caca7e10e4e61c3624eaa0941cd0) >> 128
    }
    if (abs_tick & 0x10) != 0 {
        ratio = (ratio * 0xffcb9843d60f6159c9db58835c926644) >> 128
    }
    if (abs_tick & 0x20) != 0 {
        ratio = (ratio * 0xff973b41fa98c081472e6896dfb254c0) >> 128
    }
    if (abs_tick & 0x40) != 0 {
        ratio = (ratio * 0xff2ea16466c96a3843ec78b326b52861) >> 128
    }
    if (abs_tick & 0x80) != 0 {
        ratio = (ratio * 0xfe5dee046a99a2a811c461f1969c3053) >> 128
    }
    if (abs_tick & 0x100) != 0 {
        ratio = (ratio * 0xfcbe86c7900a88aedcffc83b479aa3a4) >> 128
    }
    if (abs_tick & 0x200) != 0 {
        ratio = (ratio * 0xf987a7253ac413176f2b074cf7815e54) >> 128
    }
    if (abs_tick & 0x400) != 0 {
        ratio = (ratio * 0xf3392b0822b70005940c7a398e4b70f3) >> 128
    }
    if (abs_tick & 0x800) != 0 {
        ratio = (ratio * 0xe7159475a2c29b7443b29c7fa6e889d9) >> 128
    }
    if (abs_tick & 0x1000) != 0 {
        ratio = (ratio * 0xd097f3bdfd2022b8845ad8f792aa5825) >> 128
    }
    if (abs_tick & 0x2000) != 0 {
        ratio = (ratio * 0xa9f746462d870fdf8a65dc1f90e061e5) >> 128
    }
    if (abs_tick & 0x4000) != 0 {
        ratio = (ratio * 0x70d869a156d2a1b890bb3df62baf32f7) >> 128
    }
    if (abs_tick & 0x8000) != 0 {
        ratio = (ratio * 0x31be135f97d08fd981231505542fcfa6) >> 128
    }
    if (abs_tick & 0x10000) != 0 {
        ratio = (ratio * 0x9aa508b5b7a84e1c677de54f3e99bc9) >> 128
    }
    if (abs_tick & 0x20000) != 0 {
        ratio = (ratio * 0x5d6af8dedb81196699c329225ee604) >> 128
    }
    if (abs_tick & 0x40000) != 0 {
        ratio = (ratio * 0x2216e584f5fa1ea926041bedfe98) >> 128
    }
    if (abs_tick & 0x80000) != 0 {
        ratio = (ratio * 0x48a170391f7dc42444e8fa2) >> 128
    }

    if tick > 0 {
        ratio = U256_MAX / ratio
    }

    (ratio >> 32) + if ratio % (1 << 32) == 0 { 0 } else { 1 }
}

#[arithmetic(unchecked)]
pub fn get_tick_at_sqrt_ratio(sqrt_price_x96: u256) -> i256 {
    assert(
        sqrt_price_x96 >= MIN_SQRT_RATIO && sqrt_price_x96 < MAX_SQRT_RATIO,
    )
    let ratio = sqrt_price_x96 << 32
    let mut r = ratio
    let mut msb: u256 = 0

    while r > 1 {
        r = r >> 1
        msb = msb + 1
    }

    r = if msb >= 128 {
        ratio >> (msb - 127)
    } else {
        ratio << (127 - msb)
    }

    let msb_i: i256 = msb.downcast_unchecked()
    let mut log_2: i256 = (msb_i - 128) << 64
    let mut bit: i256 = 63
    while bit >= 50 {
        r = (r * r) >> 127
        let f = r >> 128
        let f_i: i256 = f.downcast_unchecked()
        log_2 = log_2 + (f_i << bit)
        r = r >> f
        bit = bit - 1
    }

    let log_sqrt10001 = log_2 * 255738958999603826347141
    let tick_low = (log_sqrt10001 - 3402992956809132418596140100660247210) >> 128
    let tick_hi = (log_sqrt10001 + 291339464771989622907027621153398088495) >> 128

    if tick_low == tick_hi {
        return tick_low
    }

    if get_sqrt_ratio_at_tick(tick: tick_hi) <= sqrt_price_x96 {
        return tick_hi
    }

    tick_low
}

pub fn min_sqrt_ratio() -> u256 {
    MIN_SQRT_RATIO
}

pub fn max_sqrt_ratio() -> u256 {
    MAX_SQRT_RATIO
}

msg TickMathTestMsg {
    #[selector = 0x986cfba3]
    GetSqrtRatioAtTick { tick: i256 } -> u256,

    #[selector = 0xa7398eb4]
    GetGasCostOfGetSqrtRatioAtTick { tick: i256 } -> u256,

    #[selector = 0x4f76c058]
    GetTickAtSqrtRatio { sqrtPriceX96: u256 } -> i256,

    #[selector = 0xb0622f67]
    GetGasCostOfGetTickAtSqrtRatio { sqrtPriceX96: u256 } -> u256,

    #[selector = 0xee8847ff]
    MinSqrtRatio -> u256,

    #[selector = 0x6d2cc304]
    MaxSqrtRatio -> u256,
}

pub contract TickMathTest uses (evm: Evm) {
    recv TickMathTestMsg {
        GetSqrtRatioAtTick { tick } -> u256 {
            get_sqrt_ratio_at_tick(tick)
        }

        GetGasCostOfGetSqrtRatioAtTick { tick } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            get_sqrt_ratio_at_tick(tick)
            gas_before - evm.gas()
        }

        GetTickAtSqrtRatio { sqrtPriceX96 } -> i256 {
            get_tick_at_sqrt_ratio(sqrt_price_x96: sqrtPriceX96)
        }

        GetGasCostOfGetTickAtSqrtRatio { sqrtPriceX96 } -> u256
        uses (evm)
        {
            let gas_before = evm.gas()
            get_tick_at_sqrt_ratio(sqrt_price_x96: sqrtPriceX96)
            gas_before - evm.gas()
        }

        MinSqrtRatio -> u256 {
            min_sqrt_ratio()
        }

        MaxSqrtRatio -> u256 {
            max_sqrt_ratio()
        }
    }
}
