use std::evm::{Evm, StorageMap}
use super::bit_math::{least_significant_bit, most_significant_bit}

const U256_MAX: u256 = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

pub fn int_key(_ value: i256) -> u256 {
    if value < 0 {
        return U256_MAX - (0 - value).downcast_unchecked() + 1
    }

    value.downcast_unchecked()
}

fn position(_ tick: i256) -> (i256, u256) {
    (tick >> 8, int_key(tick) & 0xff)
}

#[arithmetic(unchecked)]
pub fn flip_tick(tick: i256, tick_spacing: i256)
uses (bitmap: mut StorageMap<u256, u256>)
{
    assert(tick % tick_spacing == 0)
    let (word_pos, bit_pos) = position(tick / tick_spacing)
    let key = int_key(word_pos)
    let mask = 1 << bit_pos
    bitmap.set(key: key, value: bitmap.get(key) ^ mask)
}

#[arithmetic(unchecked)]
pub fn next_initialized_tick_within_one_word(tick: i256, tick_spacing: i256, lte: bool) -> (
    i256,
    bool,
)
uses (bitmap: StorageMap<u256, u256>)
{
    let mut compressed = tick / tick_spacing
    if tick < 0 && tick % tick_spacing != 0 {
        compressed = compressed - 1
    }

    if lte {
        let (word_pos, bit_pos) = position(compressed)
        let mask = (1 << bit_pos) - 1 + (1 << bit_pos)
        let masked = bitmap.get(key: int_key(word_pos)) & mask
        let initialized = masked != 0

        if initialized {
            let msb = most_significant_bit(masked)
            let msb_u = msb as u256
            let delta: i256 = (bit_pos - msb_u).downcast_unchecked()
            return ((compressed - delta) * tick_spacing, true)
        }

        let delta: i256 = bit_pos.downcast_unchecked()
        return ((compressed - delta) * tick_spacing, false)
    }

    let (word_pos, bit_pos) = position(compressed + 1)
    let mask = U256_MAX - ((1 << bit_pos) - 1)
    let masked = bitmap.get(key: int_key(word_pos)) & mask
    let initialized = masked != 0

    if initialized {
        let lsb = least_significant_bit(masked)
        let lsb_u = lsb as u256
        let delta: i256 = (lsb_u - bit_pos).downcast_unchecked()
        return ((compressed + 1 + delta) * tick_spacing, true)
    }

    let delta: i256 = (0xff - bit_pos).downcast_unchecked()
    ((compressed + 1 + delta) * tick_spacing, false)
}

struct TickBitmapStore { bitmap: StorageMap<u256, u256> }

msg TickBitmapTestMsg {
    #[selector = 0x8815912f]
    FlipTick { tick: i256 },

    #[selector = 0xf04bc943]
    GetGasCostOfFlipTick { tick: i256 } -> u256,

    #[selector = 0x3e7ba228]
    NextInitializedTickWithinOneWord { tick: i256, lte: bool } -> (i256, bool),

    #[selector = 0xf0fc9224]
    GetGasCostOfNextInitializedTickWithinOneWord { tick: i256, lte: bool } -> u256,

    #[selector = 0x2bdc2fd3]
    IsInitialized { tick: i256 } -> bool,
}

pub contract TickBitmapTest uses (evm: Evm) {
    mut store: TickBitmapStore,

    recv TickBitmapTestMsg {
        FlipTick { tick } uses (mut store) {
            with (store.bitmap) {
                flip_tick(tick, tick_spacing: 1)
            }
        }

        GetGasCostOfFlipTick { tick } -> u256 uses (evm, mut store) {
            let gas_before = evm.gas()
            with (store.bitmap) {
                flip_tick(tick, tick_spacing: 1)
            }
            gas_before - evm.gas()
        }

        NextInitializedTickWithinOneWord { tick, lte } -> (i256, bool)
        uses (store)
        {
            with (store.bitmap) {
                next_initialized_tick_within_one_word(tick, tick_spacing: 1, lte)
            }
        }

        GetGasCostOfNextInitializedTickWithinOneWord { tick, lte } -> u256
        uses (evm, store)
        {
            let gas_before = evm.gas()
            with (store.bitmap) {
                next_initialized_tick_within_one_word(tick, tick_spacing: 1, lte)
            }
            gas_before - evm.gas()
        }

        IsInitialized { tick } -> bool uses (store) {
            let (next, initialized) = with (store.bitmap) {
                next_initialized_tick_within_one_word(tick, tick_spacing: 1, lte: true)
            }

            next == tick && initialized
        }
    }
}
