use std::abi::sol

#[arithmetic(unchecked)]
pub fn div_rounding_up(numerator: u256, denominator: u256) -> u256 {
    if numerator % denominator > 0 {
        return (numerator / denominator) + 1
    }

    numerator / denominator
}

msg UnsafeMathEchidnaTestMsg {
    #[selector = sol("checkDivRoundingUp(uint256,uint256)")]
    CheckDivRoundingUp { x: u256, d: u256 },
}

pub contract UnsafeMathEchidnaTest {
    recv UnsafeMathEchidnaTestMsg {
        CheckDivRoundingUp { x, d } {
            assert(d > 0)
            let z = div_rounding_up(numerator: x, denominator: d)
            let diff = z - (x / d)
            if x % d == 0 {
                assert(diff == 0)
            } else {
                assert(diff == 1)
            }
        }
    }
}
